CREATE TABLE RefLocation (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	AddressLine1 VARCHAR(100) NOT NULL,
	PostalCode VARCHAR(6) NOT NULL,
	Country VARCHAR(20) NOT NULL
)

CREATE TABLE Sale(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(100),
	Price DOUBLE PRECISION NOT NULL,
	StartedOn TIMESTAMP NOT NULL,
	EditedOn TIMESTAMP NOT NULL,
	RefLocationId INT NOT NULL,
	FOREIGN KEY (RefLocationId) REFERENCES RefLocation(Id) ON DELETE CASCADE
)